//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicCatalog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public Song()
        {
            this.Albums = new HashSet<Album>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> genreId { get; set; }
        public Nullable<int> artistId { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual ICollection<Album> Albums { get; set; }
    }
}
