//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04.TodoList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories
    {
        public Categories()
        {
            this.Todos = new HashSet<Todos>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Todos> Todos { get; set; }
    }
}
