//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardAccount
    {
        public int id { get; set; }
        public string cardNumber { get; set; }
        public string cardPin { get; set; }
        public Nullable<decimal> cardCash { get; set; }
    }
}
