//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecondContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NorthwindTwinEntities : DbContext
    {
        public NorthwindTwinEntities()
            : base("name=NorthwindTwinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Alphabetical_list_of_products> Alphabetical_list_of_products { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Category_Sales_for_1997> Category_Sales_for_1997 { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Current_Product_Lists> Current_Product_Lists { get; set; }
        public DbSet<Customer_and_Suppliers_by_Cities> Customer_and_Suppliers_by_Cities { get; set; }
        public DbSet<CustomerDemographic> CustomerDemographics { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Invoice> Invoices { get; set; }
        public DbSet<Order_Details> Order_Details { get; set; }
        public DbSet<Order_Details_Extendeds> Order_Details_Extendeds { get; set; }
        public DbSet<Order_Subtotals> Order_Subtotals { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Orders_Qries> Orders_Qries { get; set; }
        public DbSet<Product_Sales_for_1997> Product_Sales_for_1997 { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Products_Above_Average_Prices> Products_Above_Average_Prices { get; set; }
        public DbSet<Products_by_Categories> Products_by_Categories { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<Sales_by_Categories> Sales_by_Categories { get; set; }
        public DbSet<Sales_Totals_by_Amounts> Sales_Totals_by_Amounts { get; set; }
        public DbSet<Shipper> Shippers { get; set; }
        public DbSet<Summary_of_Sales_by_Quarters> Summary_of_Sales_by_Quarters { get; set; }
        public DbSet<Summary_of_Sales_by_Years> Summary_of_Sales_by_Years { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Territory> Territories { get; set; }
    }
}
