//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kinds
    {
        public Kinds()
        {
            this.People = new HashSet<People>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<People> People { get; set; }
    }
}
