//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int id { get; set; }
        public string title { get; set; }
        public int year { get; set; }
        public int directorId { get; set; }
        public int leadingFemaleRoleId { get; set; }
        public int leadingMaleRoleId { get; set; }
    
        public virtual People Director { get; set; }
        public virtual People LeadingFemale { get; set; }
        public virtual People LeadingMale { get; set; }
    }
}
