//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class People
    {
        public People()
        {
            this.Movies = new HashSet<Movies>();
            this.Movies1 = new HashSet<Movies>();
            this.Movies2 = new HashSet<Movies>();
        }
    
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int studioId { get; set; }
        public int age { get; set; }
        public int kindId { get; set; }
    
        public virtual ICollection<Movies> Movies { get; set; }
        public virtual ICollection<Movies> Movies1 { get; set; }
        public virtual ICollection<Movies> Movies2 { get; set; }
        public virtual Studio Studio { get; set; }
        public virtual Kinds Kinds { get; set; }
    }
}
